name: 🚀 Deployment
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2

      - name: Install composer dependencies
        uses: php-actions/composer@v6
        with:
          command: install --ignore-platform-req=ext-intl
          php_version: "8.1"
          progress: yes

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.3.2
        with:
          server: ftp.albimediagroup.com
          username: propepa@propepa.id
          password: ABiAH}JXFV_)
